volumes:
  kromrif_planning_local_postgres_data: {}
  kromrif_planning_local_postgres_data_backups: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: kromrif_planning_local_django
    container_name: kromrif_planning_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kromrif_planning_production_postgres
    container_name: kromrif_planning_local_postgres
    volumes:
      - kromrif_planning_local_postgres_data:/var/lib/postgresql/data
      - kromrif_planning_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: kromrif_planning_local_redis
