# Generated by Django 5.1.11 on 2025-07-08 04:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character name (must be unique)', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('character_class', models.CharField(help_text='Character class (e.g., Warrior, Cleric, etc.)', max_length=32)),
                ('level', models.IntegerField(default=1, help_text='Character level')),
                ('description', models.TextField(blank=True, help_text='Optional character description or notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this character is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this character was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this character was last updated')),
                ('user', models.ForeignKey(help_text='The user who owns this character', on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='raiders_cha_user_id_12b7d1_idx'), models.Index(fields=['character_class'], name='raiders_cha_charact_ebb6b8_idx')],
            },
        ),
    ]
