# Generated by Django 5.1.11 on 2025-07-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('alt', 'Alt')], default='active', help_text='Character status', max_length=20),
        ),
    ]
