# Generated by Django 5.1.11 on 2025-07-08 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0002_add_status_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rank name (e.g., Guild Leader, Officer, Raider)', max_length=50, unique=True)),
                ('level', models.IntegerField(help_text='Hierarchy level (lower number = higher rank)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of rank permissions and responsibilities')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON field for storing rank-specific permissions')),
                ('color', models.CharField(default='#000000', help_text='Hex color code for rank display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level'],
                'indexes': [models.Index(fields=['level'], name='raiders_ran_level_99e350_idx')],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(blank=True, help_text="Character's guild rank", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='raiders.rank'),
        ),
    ]
