# Generated by Django 5.1.11 on 2025-07-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0003_add_rank_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='main_character',
            field=models.ForeignKey(blank=True, help_text='Main character (if this is an alt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_characters', to='raiders.character'),
        ),
    ]
