# Generated by Django 5.1.11 on 2025-07-08 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0004_add_main_alt_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, help_text='When the transfer occurred')),
                ('reason', models.CharField(choices=[('created', 'Character Created'), ('manual', 'Manual Transfer'), ('inactive', 'Inactive User Transfer'), ('left_guild', 'User Left Guild'), ('returned', 'Returned to Original Owner'), ('other', 'Other')], default='manual', help_text='Reason for the transfer', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transfer')),
                ('character', models.ForeignKey(help_text='The character being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='raiders.character')),
                ('new_owner', models.ForeignKey(help_text='New owner of the character', on_delete=django.db.models.deletion.CASCADE, related_name='characters_transferred_to', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(blank=True, help_text='Previous owner (null for initial creation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_transferred_from', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(blank=True, help_text='Admin/officer who initiated the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_transfers_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Character ownership history',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['character', '-transfer_date'], name='raiders_cha_charact_d154ec_idx'), models.Index(fields=['new_owner', '-transfer_date'], name='raiders_cha_new_own_4dbb0b_idx'), models.Index(fields=['previous_owner', '-transfer_date'], name='raiders_cha_previou_f36d58_idx')],
            },
        ),
    ]
