# Generated by Django 5.1.11 on 2025-07-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0005_add_character_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='rank',
        ),
    ]
