# Generated by Django 5.1.11 on 2025-07-13 04:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0007_remove_character_main_character'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', help_text='Character status', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event type (e.g., 'Main Raid', 'Off Night')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the event type')),
                ('base_points', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Base DKP points awarded for attendance', max_digits=5)),
                ('on_time_bonus', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Additional points for being on time', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this event type is currently active')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for event display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='raiders_eve_is_acti_f5545f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Specific title for this raid instance', max_length=200)),
                ('date', models.DateField(help_text='Date of the raid')),
                ('start_time', models.TimeField(help_text='Scheduled start time')),
                ('end_time', models.TimeField(blank=True, help_text='Actual end time (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the raid')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the raid', max_length=20)),
                ('parse_attendance', models.BooleanField(default=True, help_text='Automatically parse character names to award points')),
                ('points_awarded', models.BooleanField(default=False, help_text='Whether DKP points have been awarded for this raid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Type of event this raid represents', on_delete=django.db.models.deletion.CASCADE, related_name='raids', to='raiders.event')),
                ('leader', models.ForeignKey(blank=True, help_text='Raid leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_raids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RaidAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(help_text='Name of character used for this raid', max_length=64)),
                ('on_time', models.BooleanField(default=True, help_text='Whether the user arrived on time')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this attendance was recorded')),
                ('raid', models.ForeignKey(help_text='The raid this attendance record is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='raiders.raid')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who attended', on_delete=django.db.models.deletion.CASCADE, related_name='raid_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raid Attendance',
                'verbose_name_plural': 'Raid Attendance Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='raid',
            index=models.Index(fields=['date', 'status'], name='raiders_rai_date_c11c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='raid',
            index=models.Index(fields=['event', 'date'], name='raiders_rai_event_i_18dc14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='raid',
            unique_together={('event', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='raidattendance',
            index=models.Index(fields=['raid', 'user'], name='raiders_rai_raid_id_342b26_idx'),
        ),
        migrations.AddIndex(
            model_name='raidattendance',
            index=models.Index(fields=['character_name'], name='raiders_rai_charact_f151a9_idx'),
        ),
        migrations.AddIndex(
            model_name='raidattendance',
            index=models.Index(fields=['created_at'], name='raiders_rai_created_355d09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='raidattendance',
            unique_together={('raid', 'user')},
        ),
    ]
