# Generated by Django 5.1.11 on 2025-07-13 04:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0008_alter_character_status_event_raid_raidattendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the item')),
                ('suggested_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suggested DKP cost for this item', max_digits=10)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', help_text='Rarity of the item', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently active for distribution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['rarity', 'is_active'], name='raiders_ite_rarity_082df4_idx'), models.Index(fields=['suggested_cost'], name='raiders_ite_suggest_b19441_idx')],
            },
        ),
        migrations.CreateModel(
            name='LootDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(help_text='Character name at time of distribution', max_length=64)),
                ('point_cost', models.DecimalField(decimal_places=2, help_text='DKP points spent on this item', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of items distributed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the distribution')),
                ('distributed_at', models.DateTimeField(auto_now_add=True, help_text='When the item was distributed')),
                ('discord_message_id', models.CharField(blank=True, help_text='Discord message ID for reference', max_length=100)),
                ('discord_channel_id', models.CharField(blank=True, help_text='Discord channel ID where distribution was announced', max_length=100)),
                ('distributed_by', models.ForeignKey(blank=True, help_text='Who distributed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loot_distributed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The item that was distributed', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='raiders.item')),
                ('raid', models.ForeignKey(blank=True, help_text='The raid where this item was distributed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loot_distributions', to='raiders.raid')),
                ('user', models.ForeignKey(help_text='The user who received the item', on_delete=django.db.models.deletion.CASCADE, related_name='loot_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loot Distribution',
                'verbose_name_plural': 'Loot Distributions',
                'ordering': ['-distributed_at'],
                'indexes': [models.Index(fields=['user', '-distributed_at'], name='raiders_loo_user_id_764786_idx'), models.Index(fields=['item', '-distributed_at'], name='raiders_loo_item_id_989e5b_idx'), models.Index(fields=['raid', '-distributed_at'], name='raiders_loo_raid_id_899df2_idx'), models.Index(fields=['character_name'], name='raiders_loo_charact_c9ca63_idx')],
            },
        ),
    ]
