# Generated by Django 5.1.11 on 2025-07-13 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0009_item_lootdistribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LootAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('item_created', 'Item Created'), ('item_updated', 'Item Updated'), ('item_deleted', 'Item Deleted'), ('item_activated', 'Item Activated'), ('item_deactivated', 'Item Deactivated'), ('distribution_created', 'Loot Distribution Created'), ('distribution_updated', 'Loot Distribution Updated'), ('distribution_deleted', 'Loot Distribution Deleted'), ('distribution_refunded', 'Loot Distribution Refunded'), ('points_deducted', 'DKP Points Deducted'), ('points_refunded', 'DKP Points Refunded'), ('admin_action', 'Administrative Action'), ('system_action', 'System Action')], help_text='Type of action performed', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('character_name', models.CharField(blank=True, help_text='Character name at time of action', max_length=64)),
                ('point_cost', models.DecimalField(blank=True, decimal_places=2, help_text='DKP cost involved in the action (if applicable)', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Quantity of items involved (if applicable)', null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values before the change (JSON format)')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values after the change (JSON format)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string for web-based actions')),
                ('discord_context', models.JSONField(blank=True, default=dict, help_text='Discord-related context (message ID, channel, etc.)')),
                ('request_id', models.CharField(blank=True, help_text='Request ID for tracking related actions', max_length=100)),
                ('affected_user', models.ForeignKey(blank=True, help_text='User affected by the action (recipient of loot, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loot_audit_affected', to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(blank=True, help_text='Related loot distribution (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='raiders.lootdistribution')),
                ('item', models.ForeignKey(blank=True, help_text='Related item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='raiders.item')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loot_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('raid', models.ForeignKey(blank=True, help_text='Related raid (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loot_audit_logs', to='raiders.raid')),
            ],
            options={
                'verbose_name': 'Loot Audit Log',
                'verbose_name_plural': 'Loot Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', '-timestamp'], name='raiders_loo_action__30cee1_idx'), models.Index(fields=['performed_by', '-timestamp'], name='raiders_loo_perform_a6691c_idx'), models.Index(fields=['affected_user', '-timestamp'], name='raiders_loo_affecte_7ecbef_idx'), models.Index(fields=['item', '-timestamp'], name='raiders_loo_item_id_6c0511_idx'), models.Index(fields=['distribution', '-timestamp'], name='raiders_loo_distrib_d19f32_idx'), models.Index(fields=['raid', '-timestamp'], name='raiders_loo_raid_id_25b3b6_idx'), models.Index(fields=['character_name', '-timestamp'], name='raiders_loo_charact_9c1c84_idx'), models.Index(fields=['-timestamp'], name='raiders_loo_timesta_eb80c5_idx')],
            },
        ),
    ]
