# Generated by Django 5.1.11 on 2025-07-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0010_lootauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'permissions': [('can_use_discord_api', 'Can use Discord bot API'), ('can_manage_discord_links', 'Can manage Discord user links'), ('can_view_member_data', 'Can view detailed member data'), ('can_modify_member_status', 'Can modify member status')]},
        ),
    ]
