# Generated by Django 5.1.11 on 2025-07-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0011_add_discord_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='main_character',
            field=models.ForeignKey(blank=True, help_text='Main character if this is an alt (null if this is a main character)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_characters', to='raiders.character'),
        ),
    ]
