# Generated by Django 5.1.11 on 2025-07-14 14:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0012_add_main_character_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(default=django.utils.timezone.now, help_text='Date this summary is calculated for')),
                ('attendance_rate_7d', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Attendance rate over last 7 days (0-100%)', max_digits=5)),
                ('attendance_rate_30d', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Attendance rate over last 30 days (0-100%)', max_digits=5)),
                ('attendance_rate_60d', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Attendance rate over last 60 days (0-100%)', max_digits=5)),
                ('attendance_rate_90d', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Attendance rate over last 90 days (0-100%)', max_digits=5)),
                ('attendance_rate_lifetime', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime attendance rate (0-100%)', max_digits=5)),
                ('total_raids_7d', models.PositiveIntegerField(default=0, help_text='Total raids available in last 7 days')),
                ('attended_raids_7d', models.PositiveIntegerField(default=0, help_text='Raids attended in last 7 days')),
                ('total_raids_30d', models.PositiveIntegerField(default=0, help_text='Total raids available in last 30 days')),
                ('attended_raids_30d', models.PositiveIntegerField(default=0, help_text='Raids attended in last 30 days')),
                ('total_raids_60d', models.PositiveIntegerField(default=0, help_text='Total raids available in last 60 days')),
                ('attended_raids_60d', models.PositiveIntegerField(default=0, help_text='Raids attended in last 60 days')),
                ('total_raids_90d', models.PositiveIntegerField(default=0, help_text='Total raids available in last 90 days')),
                ('attended_raids_90d', models.PositiveIntegerField(default=0, help_text='Raids attended in last 90 days')),
                ('total_raids_lifetime', models.PositiveIntegerField(default=0, help_text='Total raids available since member join')),
                ('attended_raids_lifetime', models.PositiveIntegerField(default=0, help_text='Total raids attended since member join')),
                ('is_voting_eligible', models.BooleanField(default=False, help_text='Whether member is eligible to vote (≥15% attendance in 30 days)')),
                ('current_attendance_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive raids attended')),
                ('longest_attendance_streak', models.PositiveIntegerField(default=0, help_text='Longest consecutive raids attended streak')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this summary was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this summary was first created')),
                ('user', models.ForeignKey(help_text='The user whose attendance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Attendance Summary',
                'verbose_name_plural': 'Member Attendance Summaries',
                'ordering': ['-summary_date', '-attendance_rate_30d'],
                'indexes': [models.Index(fields=['user', 'summary_date'], name='raiders_mem_user_id_52126a_idx'), models.Index(fields=['summary_date'], name='raiders_mem_summary_fdd025_idx'), models.Index(fields=['attendance_rate_30d'], name='raiders_mem_attenda_e44682_idx'), models.Index(fields=['attendance_rate_90d'], name='raiders_mem_attenda_0009ef_idx'), models.Index(fields=['is_voting_eligible'], name='raiders_mem_is_voti_1ed82c_idx'), models.Index(fields=['user', '-summary_date'], name='raiders_mem_user_id_4fbf5a_idx')],
                'unique_together': {('user', 'summary_date')},
            },
        ),
    ]
