# Generated by Django 5.1.11 on 2025-07-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiders', '0014_add_recruitment_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-submitted_at'], 'permissions': [('review_applications', 'Can review and process applications'), ('manage_applications', 'Can manage all aspects of applications'), ('vote_on_applications', 'Can vote on applications'), ('view_application_votes', 'Can view voting results'), ('view_sensitive_application_info', 'Can view sensitive applicant information')], 'verbose_name': 'Guild Application', 'verbose_name_plural': 'Guild Applications'},
        ),
        migrations.AlterModelOptions(
            name='applicationvote',
            options={'ordering': ['-voted_at'], 'permissions': [('view_application_vote_details', 'Can view detailed vote information'), ('manage_application_votes', 'Can manage and modify application votes')], 'verbose_name': 'Application Vote', 'verbose_name_plural': 'Application Votes'},
        ),
    ]
