# Generated by Django 5.1.11 on 2025-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord Avatar Hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_discriminator',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Discord Discriminator'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Discord Username'),
        ),
    ]
