# Generated by Django 5.1.11 on 2025-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_discord_avatar_user_discord_discriminator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role_group',
            field=models.CharField(choices=[('developer', 'Developer'), ('officer', 'Officer'), ('recruiter', 'Recruiter'), ('member', 'Member'), ('applicant', 'Applicant'), ('guest', 'Guest')], default='guest', help_text="User's role within the guild hierarchy", max_length=20, verbose_name='Role Group'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['discord_id'], name='users_discord_fa9188_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['discord_username'], name='users_discord_f72c01_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role_group'], name='users_role_gr_35bcd0_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
