# Generated by Django 5.1.11 on 2025-07-06 17:05

import kromrif_planning.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250706_1558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', kromrif_planning.users.models.UserManager()),
            ],
        ),
    ]
